language: node_js
node_js:
- '0.10'
before_install:
- openssl aes-256-cbc -K $encrypted_9e817d28757a_key -iv $encrypted_9e817d28757a_iv
  -in .ftppass.enc -out .ftppass -d
- npm install -g grunt-cli
- gem install sass
before_script:
- npm install -g bower
- bower install
